# Generated by Django 5.0.14 on 2026-02-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(
                blank=True, default="/fintrellis.gif", max_length=500
            ),
        ),
    ]
