MAX_TITLE_LENGTH = 255
MAX_SLUG_LENGTH = 255
MAX_EXCERPT_LENGTH = 500
MAX_CATEGORY_LENGTH = 50
MIN_CONTENT_LENGTH = 10
AUTO_EXCERPT_LENGTH = 200
MAX_THUMBNAIL_SIZE_MB = 5
ALLOWED_THUMBNAIL_TYPES = ["image/jpeg", "image/png", "image/webp"]
